#source file for bash's aliases
alias mf='cd ~/Desktop'
alias open='xdg-open'
alias cron='crontab ~/.crontab'
alias driver='sudo pacman -S $(cat ~/drivers.txt)'
alias package='sudo pacman -S $(cat ~/packages.txt)'
alias service='systemctl enable --now $(cat ~/service.txt)'
alias install='driver && package && service'
alias update='paru && clean'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias mirror='sudo reflector --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist'
alias sc='flameshot gui --clipboard'
alias ssr='simplescreenrecorder'
alias em='emacsclient -c -a emacs'
alias gc='git checkout -- '
alias gs='git status'
alias gd='git diff'
