#source file for bash's aliases
alias mf='cd ~/Desktop'
alias ssr='simplescreenrecorder'
alias open='xdg-open'
alias driver='sudo pacman -S $(cat ~/system.txt)'
alias install='sudo pacman -S $(cat ~/packages.txt)'
alias enable='systemctl enable --now $(cat ~/service.txt)'
alias update='paru && clean'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias mirror='sudo reflector --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist'
alias em='emacsclient -c -a emacs'
alias gc='git checkout -- '
alias gs='git status'
alias gd='git diff'
