-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    splash = false,
    wallpaper = {
        path = "~/wallpaper/wp.jpg",
        fit_mode = "cover",
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output
