-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

--AUTOGENERATED HYPR CONFIG.

--PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,

--OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

--

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

--

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Execute your favorite apps at launch


-- Source a file (multi-file configs)

-- source = ~/.config/hypr/myColors.conf

-- Some default env vars.

hl.env("XCURSOR_SIZE", 24)

-- default wallpaper disable

hl.config({
    misc = {
        disable_hyprland_logo = true,
    },
})

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        -- grp:caps_toggle
        kb_rules = "",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
    },
})

hl.config({
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 1,
        gaps_out = 1,
        border_size = 1,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

hl.config({
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 0,
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
        },
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
    },
})

hl.config({
    animations = {
        enabled = true,
        -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})

hl.config({
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        preserve_split = true,
        -- you probably want this
    },
})

hl.config({
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        new_status = "slave",
    },
})

-- Fix hyprland workspace_swipe removed
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

--device:epic-mouse-v1 {

--    sensitivity = -0.5

--}

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

local mainMod = "ALT"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.window.close())

-- default is mod + C

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("fuzzel"))

-- default app launcher is wofi

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- dwindle

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- My config

-- Toggle waybar

hl.bind(mainMod .. " + " .. "X", hl.dsp.exec_cmd("killall waybar || waybar"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "X", hl.dsp.exec_cmd("pkill -SIGUSR1 '^waybar$' || waybar"))

-- Toggle live wallpaper

hl.bind(mainMod .. " + " .. "Z", hl.dsp.exec_cmd("livewp"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Z", hl.dsp.exec_cmd("killall mpvpaper || livewp"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Z", hl.dsp.exec_cmd("killall hyprpaper mpvpaper waybar"))

-- Switch tabs

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Tab", hl.dsp.focus({ workspace = "m-1" }))

hl.bind(mainMod .. " + " .. "Tab", hl.dsp.focus({ workspace = "m+1" }))

hl.bind(mainMod .. " + " .. "Space", hl.dsp.window.cycle_next())

hl.bind(mainMod .. " + " .. "E", hl.dsp.window.fullscreen())

--fullscreen but don't block waybar

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.window.fullscreen())

-- volume settings

hl.bind("F1", hl.dsp.exec_cmd("amixer -q set Master toggle && vol"))

hl.bind(mainMod .. " + " .. "F1", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ 100% && vol"))

-- Set max vol to 100%

hl.bind("F2", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -1% && vol"), { repeating = true })

hl.bind("F3", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +1% && vol"), { repeating = true })

hl.bind("F4", hl.dsp.exec_cmd("amixer set Capture toggle"))

hl.bind(mainMod .. " + " .. "F5", hl.dsp.exec_cmd("rog-control-center"))

-- brightness settings

hl.bind("F6", hl.dsp.exec_cmd("bright"))

hl.bind("F7", hl.dsp.exec_cmd("bright 5000-"))

hl.bind("F8", hl.dsp.exec_cmd("bright 5000+"))

-- modes

hl.bind(mainMod .. " + " .. "F9", hl.dsp.submap("clean"))

hl.define_submap("clean", function()
    hl.bind(mainMod .. " + " .. "F9", hl.dsp.submap("reset"))
end)


hl.bind(mainMod .. " + " .. "F10", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + " .. "F11", hl.dsp.exec_cmd("systemctl suspend"))

hl.bind(mainMod .. " + " .. "F12", hl.dsp.exec_cmd("wifi -t"))

-- capture screen

hl.bind(mainMod .. " + " .. "I", hl.dsp.exec_cmd("shot"))

hl.bind(mainMod .. " + " .. "O", hl.dsp.exec_cmd("obs"))

-- app shortcuts

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("qutebrowser"))

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("spotify"))

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("firefox"))

hl.bind(mainMod .. " + " .. "F", hl.dsp.exec_cmd("kitty nvim"))

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("qbittorrent"))

hl.bind(mainMod .. " + " .. "Y", hl.dsp.exec_cmd("kitty yazi"))

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("pavucontrol"))

hl.bind(mainMod .. " + " .. "G", hl.dsp.exec_cmd("toggle"))

-- Move window with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "l" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "u" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "d" }))

-- swaync commands

hl.bind("CTRL" .. " + " .. "D", hl.dsp.exec_cmd("swaync-client -C"))

hl.bind("CTRL + SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("swaync-client -t"))

-- fix qutebrowser scaling issue

hl.env("QT_SCALE_FACTOR_ROUNDING_POLICY", "RoundPreferFloor")

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar & fcitx5 & livewp & systemctl --user start hyprpolkitagent")
end)
